exclude: "^docs/|/migrations/|/output/|/upload/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: poetry-export
        args: ["-f", "requirements.txt", "--without-hashes", "-o", "requirements.txt", "--dev"]
        verbose: true

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
