# Generated by Django 4.1.5 on 2023-01-05 19:43

from django.db import migrations


def create_templates(apps, schema_editor):
    ProgrammingLanguage = apps.get_model("project", "ProgrammingLanguage")
    data = ["Java", "Python"]
    for d in data:
        lang = ProgrammingLanguage()
        lang.name = d
        lang.save()

    CodeTemplate = apps.get_model("project", "CodeTemplate")
    data = [
        ("Java", "https://github.com/HenryJobst/cookiecutter-java-springboot.git"),
        ("Python", "https://github.com/HenryJobst/cookiecutter-django.git"),
    ]
    for name, path in data:
        lang = ProgrammingLanguage.objects.get(name=name)
        templ = CodeTemplate()
        templ.programming_language = lang
        templ.path = path
        templ.save()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("project", "0040_alter_projectsettings_admin_password"),
    ]

    operations = [
        migrations.RunPython(create_templates),
    ]
