# Generated by Django 4.1.4 on 2022-12-16 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("is_main_entity", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("creation_date", models.DateTimeField()),
                ("modified_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationFile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_path", models.FilePathField(unique=True, verbose_name="")),
                ("file", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="TransformationSheet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("index", models.IntegerField()),
                (
                    "transformation_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.transformationfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationHeadline",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("row_index", models.IntegerField()),
                (
                    "transformation_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.transformationsheet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transformationfile",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.transformationmapping",
            ),
        ),
        migrations.CreateModel(
            name="TransformationColumn",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("column_index", models.IntegerField()),
                (
                    "transformation_headline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.transformationheadline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(default="admin", max_length=60)),
                ("admin_password", models.CharField(max_length=100)),
                ("demo_user_name", models.CharField(default="demo", max_length=60)),
                ("demo_user_password", models.CharField(max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelField",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("is_primary_key", models.BooleanField()),
                ("datatype", models.CharField(default="CharField", max_length=60)),
                ("datatype_length", models.IntegerField(null=True)),
                ("is_foreign_key", models.BooleanField(default=False)),
                ("foreign_key_entity", models.CharField(max_length=100)),
                ("foreign_key_id", models.CharField(max_length=100)),
                ("is_unique", models.BooleanField(default=False)),
                ("use_index", models.BooleanField(default=False)),
                ("validation_pattern", models.CharField(max_length=100)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="project.model"
                    ),
                ),
                (
                    "transformation_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.transformationcolumn",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="model",
            name="transformation_headline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.transformationheadline",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.transformationmapping",
            ),
        ),
    ]
