# Generated by Django 4.1.4 on 2022-12-24 09:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    replaces = [
        ("project", "0001_initial"),
        ("project", "0002_remove_modelfield_is_primary_key_and_more"),
        ("project", "0003_alter_model_options_alter_modelfield_options_and_more"),
        ("project", "0004_model_project"),
        ("project", "0005_alter_projectsettings_admin_password_and_more"),
        ("project", "0006_alter_projectsettings_admin_password_and_more"),
        ("project", "0007_alter_projectsettings_admin_name_and_more"),
        ("project", "0008_remove_model_project_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TransformationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FilePathField(unique=True, verbose_name="")),
                ("file", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="TransformationMapping",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                (
                    "transformation_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.transformationfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationHeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                (
                    "transformation_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.transformationsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransformationColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_index", models.IntegerField()),
                (
                    "transformation_headline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.transformationheadline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transformationfile",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.transformationmapping",
            ),
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("is_main_entity", models.BooleanField(default=False)),
                (
                    "transformation_headline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.transformationheadline",
                    ),
                ),
                (
                    "transformation_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.transformationmapping",
                    ),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "unique_together": {("index", "transformation_mapping")},
            },
        ),
        migrations.CreateModel(
            name="ModelField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("datatype", models.CharField(default="CharField", max_length=60)),
                ("datatype_length", models.IntegerField(null=True)),
                ("default_value", models.CharField(max_length=100, null=True)),
                ("is_foreign_key", models.BooleanField(default=False)),
                ("foreign_key_entity", models.CharField(max_length=100)),
                ("foreign_key_id", models.CharField(max_length=100)),
                ("is_unique", models.BooleanField(default=False)),
                ("use_index", models.BooleanField(default=False)),
                ("validation_pattern", models.CharField(max_length=100)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.model"
                    ),
                ),
                (
                    "transformation_column",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.transformationcolumn",
                    ),
                ),
                ("show_in_list", models.BooleanField(default=True)),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "unique_together": {("index", "model")},
            },
        ),
        migrations.CreateModel(
            name="ProjectSettings",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="project.project",
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(
                        default="admin",
                        max_length=60,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                (
                    "admin_password",
                    models.CharField(
                        default="1ba369c86dd649c39a63774d",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "demo_user_name",
                    models.CharField(
                        default="demo",
                        max_length=60,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
                (
                    "demo_user_password",
                    models.CharField(
                        default="59fc92868a2f47fd8d315910",
                        help_text="Kein Passwort setzen, um keinen Demo-User anzulegen!",
                        max_length=100,
                        null=True,
                        validators=[project.models.NullOrMinLengthValidator(6)],
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(
                        max_length=100,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(4)],
                    ),
                ),
            ],
        ),
    ]
