# Generated by Django 4.1.4 on 2022-12-23 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_modelfield_is_primary_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"ordering": ["index"]},
        ),
        migrations.AlterModelOptions(
            name="modelfield",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="model",
            name="index",
            field=models.PositiveSmallIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="modelfield",
            name="index",
            field=models.PositiveSmallIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("index", "transformation_mapping")},
        ),
        migrations.AlterUniqueTogether(
            name="modelfield",
            unique_together={("index", "model")},
        ),
    ]
