# Generated by Django 4.1.4 on 2022-12-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_model_options_alter_modelfield_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
            ),
            preserve_default=False,
        ),
    ]
