# Generated by Django 4.1.4 on 2022-12-23 22:58

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_projectsettings_admin_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_name",
            field=models.CharField(
                default="admin",
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="08208a32716749b8ac3d08a4",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="demo_user_name",
            field=models.CharField(
                default="demo",
                max_length=60,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="demo_user_password",
            field=models.CharField(
                default="9ae4955f5051441884b46702",
                help_text="Kein Passwort setzen, um keinen Demo-User anzulegen!",
                max_length=100,
                null=True,
                validators=[project.models.NullOrMinLengthValidator(6)],
            ),
        ),
    ]
