# Generated by Django 4.1.4 on 2022-12-25 09:02

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_squashed_0008_remove_model_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="is_main_entity",
            field=models.BooleanField(default=False, verbose_name="Haupt-Tabelle?"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="b7e211d02490420caaa5f1c6",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="demo_user_name",
            field=models.CharField(
                blank=True,
                default="demo",
                max_length=60,
                null=True,
                validators=[project.models.NullOrMinLengthValidator(4)],
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="demo_user_password",
            field=models.CharField(
                blank=True,
                help_text="Kein Passwort setzen, um keinen Demo-User anzulegen!",
                max_length=100,
                null=True,
                validators=[project.models.NullOrMinLengthValidator(6)],
            ),
        ),
    ]
