# Generated by Django 4.1.4 on 2022-12-26 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_model_transformation_mapping_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModelField",
            new_name="Field",
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="4dca2c69f5e9404ca555a304",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
    ]
