# Generated by Django 4.1.4 on 2022-12-26 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_rename_modelfield_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="foreign_key_id",
        ),
        migrations.AlterField(
            model_name="field",
            name="foreign_key_entity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="field",
            name="validation_pattern",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="0bc631e29aaa44068c519788",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
    ]
