# Generated by Django 4.1.4 on 2022-12-26 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_alter_field_datatype_alter_field_datatype_length_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="is_foreign_key",
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="378c9f4c766f4a9293e2f6fa",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
    ]
