# Generated by Django 4.1.4 on 2022-12-28 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import project.models
import project.services.import_file


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_remove_transformationfile_file_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="transformation_headline",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.transformationheadline",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="86af290ef7c04067bac93ea1",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
        migrations.AlterField(
            model_name="transformationcolumn",
            name="transformation_headline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="project.transformationheadline",
            ),
        ),
        migrations.AlterField(
            model_name="transformationfile",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="project.transformationmapping",
                validators=[project.models.validate_file_type],
            ),
        ),
        migrations.AlterField(
            model_name="transformationheadline",
            name="transformation_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="headlines",
                to="project.transformationsheet",
            ),
        ),
        migrations.AlterField(
            model_name="transformationsheet",
            name="transformation_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheets",
                to="project.transformationfile",
            ),
        ),
    ]
