# Generated by Django 4.1.4 on 2022-12-28 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import project.models
import project.services.import_file


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0020_alter_field_datatype_alter_field_foreign_key_entity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="7a264afabc504e0ba77384fd",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
        migrations.AlterField(
            model_name="transformationfile",
            name="file",
            field=models.FileField(
                max_length=200,
                unique=True,
                upload_to="",
                validators=[project.models.validate_file_type],
                verbose_name="Datei",
            ),
        ),
        migrations.AlterField(
            model_name="transformationfile",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="project.transformationmapping",
            ),
        ),
    ]
