# Generated by Django 4.1.4 on 2022-12-28 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_alter_projectsettings_admin_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="datatype",
            field=models.IntegerField(
                choices=[
                    (0, "Keiner"),
                    (1, "BigIntegerField"),
                    (2, "BinaryField"),
                    (3, "BooleanField"),
                    (4, "CharField"),
                    (5, "CommaSeparatedIntegerField"),
                    (6, "DateField"),
                    (7, "DateTimeField"),
                    (8, "DecimalField"),
                    (9, "DurationField"),
                    (10, "EmailField"),
                    (11, "Field"),
                    (12, "FilePathField"),
                    (13, "FloatField"),
                    (14, "GenericIPAddressField"),
                    (15, "IPAddressField"),
                    (16, "IntegerField"),
                    (17, "NullBooleanField"),
                    (18, "PositiveBigIntegerField"),
                    (19, "PositiveIntegerField"),
                    (20, "PositiveSmallIntegerField"),
                    (21, "SlugField"),
                    (22, "SmallAutoField"),
                    (23, "SmallIntegerField"),
                    (24, "TextField"),
                    (25, "TimeField"),
                    (26, "URLField"),
                    (27, "UUIDField"),
                ],
                default=4,
                verbose_name="Datentyp",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="85cd7122a5cb4ee0b34af5d4",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
