# Generated by Django 4.1.4 on 2022-12-30 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_alter_field_datatype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="transformation_headline",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="models",
                to="project.transformationheadline",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="da6d6495808a4c23ab4b5f1c",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
