# Generated by Django 4.1.4 on 2022-12-31 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_alter_projectsettings_admin_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transformationcolumn",
            options={"ordering": ["transformation_headline", "column_index"]},
        ),
        migrations.AlterModelOptions(
            name="transformationheadline",
            options={"ordering": ["transformation_sheet", "row_index"]},
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="37b7307c17704a8dab2b8cfc",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transformationcolumn",
            unique_together={("transformation_headline", "column_index")},
        ),
        migrations.AlterUniqueTogether(
            name="transformationheadline",
            unique_together={("transformation_sheet", "row_index")},
        ),
    ]
