# Generated by Django 4.1.4 on 2022-12-31 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_alter_transformationcolumn_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transformationfile",
            options={"ordering": ["transformation_mapping", "file"]},
        ),
        migrations.AlterModelOptions(
            name="transformationsheet",
            options={"ordering": ["transformation_file", "index"]},
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="d7b68a4231b446d0826890fe",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transformationfile",
            unique_together={("transformation_mapping", "file")},
        ),
        migrations.AlterUniqueTogether(
            name="transformationsheet",
            unique_together={("transformation_file", "index")},
        ),
    ]
