# Generated by Django 4.1.4 on 2022-12-31 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_alter_transformationfile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={"ordering": ["index", "model"]},
        ),
        migrations.AlterModelOptions(
            name="model",
            options={"ordering": ["index", "transformation_mapping"]},
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="5c3fc8e33f4140d8b3beaaa9",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
