# Generated by Django 4.1.4 on 2022-12-31 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_alter_field_options_alter_model_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="transformation_headline",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model",
                to="project.transformationheadline",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="defaf2d216c941ddac08a6ea",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
