# Generated by Django 4.1.4 on 2023-01-03 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0032_alter_projectsettings_admin_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="exclude",
            field=models.BooleanField(default=False, verbose_name="nicht anlegen"),
        ),
        migrations.AddField(
            model_name="field",
            name="show_in_detail",
            field=models.BooleanField(
                default=True, verbose_name="in Detailansicht anzeigen?"
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="exclude",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transformationcolumn",
            name="exclude",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transformationheadline",
            name="exclude",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transformationsheet",
            name="exclude",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="field",
            name="show_in_list",
            field=models.BooleanField(default=True, verbose_name="in Liste anzeigen?"),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="01f332f1e83745ce8574abae",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
