# Generated by Django 4.1.5 on 2023-01-03 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0033_field_exclude_field_show_in_detail_model_exclude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="field",
            old_name="datatype_length",
            new_name="max_length",
        ),
        migrations.AddField(
            model_name="field",
            name="blank",
            field=models.BooleanField(
                default=False, verbose_name="leeres Eingabefeld zulässig?"
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="choices",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="field",
            name="decimal_places",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Anzahl der Nachkommastellen bei einer Dezimalzahl",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="max_digits",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Anzahl der Stellen bei einer Dezimalzahl",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="null",
            field=models.BooleanField(
                default=False, verbose_name="leerer Spaltenwert zulässig?"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="datatype",
            field=models.IntegerField(
                choices=[
                    (0, "Keiner"),
                    (1, "BigIntegerField"),
                    (2, "BinaryField"),
                    (3, "BooleanField"),
                    (4, "CharField"),
                    (5, "CommaSeparatedIntegerField"),
                    (6, "DateField"),
                    (7, "DateTimeField"),
                    (8, "DecimalField"),
                    (9, "DurationField"),
                    (10, "EmailField"),
                    (11, "Field"),
                    (12, "FilePathField"),
                    (13, "FloatField"),
                    (14, "GenericIPAddressField"),
                    (15, "IPAddressField"),
                    (16, "IntegerField"),
                    (17, "NullBooleanField"),
                    (18, "PositiveBigIntegerField"),
                    (19, "PositiveIntegerField"),
                    (20, "PositiveSmallIntegerField"),
                    (21, "SlugField"),
                    (22, "SmallAutoField"),
                    (23, "SmallIntegerField"),
                    (24, "TextField"),
                    (25, "TimeField"),
                    (26, "URLField"),
                    (27, "UUIDField"),
                ],
                default="C",
                verbose_name="Datentyp",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="is_unique",
            field=models.BooleanField(default=False, verbose_name="Eindeutig?"),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="622783f19c614658830598b1",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
