# Generated by Django 4.1.5 on 2023-01-04 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0034_rename_datatype_length_field_max_length_field_blank_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="exclude",
            field=models.BooleanField(default=False, verbose_name="nicht anlegen"),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="12ec7e0c191d4a47be49785c",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
