# Generated by Django 4.1.5 on 2023-01-04 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0035_model_description_alter_model_exclude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Beschreibung"
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="2b207fae40664b1dbaffb437",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
