# Generated by Django 4.1.5 on 2023-01-04 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_field_description_alter_model_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="choices",
            field=models.JSONField(blank=True, null=True, verbose_name="Auswahlwerte"),
        ),
        migrations.AlterField(
            model_name="field",
            name="datatype",
            field=models.IntegerField(
                choices=[
                    (0, "Keiner"),
                    (1, "BigIntegerField"),
                    (2, "BinaryField"),
                    (3, "BooleanField"),
                    (4, "CharField"),
                    (5, "CommaSeparatedIntegerField"),
                    (6, "DateField"),
                    (7, "DateTimeField"),
                    (8, "DecimalField"),
                    (9, "DurationField"),
                    (10, "EmailField"),
                    (11, "Field"),
                    (12, "FilePathField"),
                    (13, "FloatField"),
                    (14, "GenericIPAddressField"),
                    (15, "IPAddressField"),
                    (16, "IntegerField"),
                    (17, "NullBooleanField"),
                    (18, "PositiveBigIntegerField"),
                    (19, "PositiveIntegerField"),
                    (20, "PositiveSmallIntegerField"),
                    (21, "SlugField"),
                    (22, "SmallAutoField"),
                    (23, "SmallIntegerField"),
                    (24, "TextField"),
                    (25, "TimeField"),
                    (26, "URLField"),
                    (27, "UUIDField"),
                    (28, "AutoField"),
                    (29, "BigAutoField"),
                    (30, "FileField"),
                    (31, "JSONField"),
                ],
                default="C",
                verbose_name="Datentyp",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="foreign_key_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.model",
                verbose_name="Fremdschlüssel",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="1ea75e6b16d64da6ae9ea056",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
    ]
