# Generated by Django 4.1.5 on 2023-01-05 21:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0037_alter_field_choices_alter_field_datatype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Programmiersprache",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="Administrator-Passwort",
            ),
        ),
        migrations.CreateModel(
            name="CodeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="URL/Pfad",
                    ),
                ),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.programminglanguage",
                    ),
                ),
            ],
        ),
    ]
