# Generated by Django 4.1.5 on 2023-01-07 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0038_programminglanguage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["index", "model"],
                "verbose_name": "field",
                "verbose_name_plural": "fields",
            },
        ),
        migrations.AlterModelOptions(
            name="model",
            options={
                "ordering": ["index", "transformation_mapping"],
                "verbose_name": "model",
                "verbose_name_plural": "models",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectsettings",
            options={
                "verbose_name": "project settings",
                "verbose_name_plural": "project settings",
            },
        ),
        migrations.AlterModelOptions(
            name="transformationfile",
            options={
                "ordering": ["transformation_mapping", "file"],
                "verbose_name": "file",
                "verbose_name_plural": "files",
            },
        ),
        migrations.AddField(
            model_name="codetemplate",
            name="name",
            field=models.CharField(
                max_length=60,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="internationalizable",
            field=models.BooleanField(
                default=False, verbose_name="internationalizable"
            ),
        ),
        migrations.AlterField(
            model_name="codetemplate",
            name="path",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="path",
            ),
        ),
        migrations.AlterField(
            model_name="codetemplate",
            name="programming_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programming_languages",
                to="project.programminglanguage",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="blank",
            field=models.BooleanField(
                default=False, verbose_name="allow empty values in form"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="choices",
            field=models.JSONField(
                blank=True, null=True, verbose_name="selection values"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="field",
            name="datatype",
            field=models.IntegerField(
                choices=[
                    (0, "Keiner"),
                    (1, "BigIntegerField"),
                    (2, "BinaryField"),
                    (3, "BooleanField"),
                    (4, "CharField"),
                    (5, "CommaSeparatedIntegerField"),
                    (6, "DateField"),
                    (7, "DateTimeField"),
                    (8, "DecimalField"),
                    (9, "DurationField"),
                    (10, "EmailField"),
                    (11, "Field"),
                    (12, "FilePathField"),
                    (13, "FloatField"),
                    (14, "GenericIPAddressField"),
                    (15, "IPAddressField"),
                    (16, "IntegerField"),
                    (17, "NullBooleanField"),
                    (18, "PositiveBigIntegerField"),
                    (19, "PositiveIntegerField"),
                    (20, "PositiveSmallIntegerField"),
                    (21, "SlugField"),
                    (22, "SmallAutoField"),
                    (23, "SmallIntegerField"),
                    (24, "TextField"),
                    (25, "TimeField"),
                    (26, "URLField"),
                    (27, "UUIDField"),
                    (28, "AutoField"),
                    (29, "BigAutoField"),
                    (30, "FileField"),
                    (31, "JSONField"),
                ],
                default="C",
                verbose_name="data type",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="decimal_places",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="decimal places"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="default_value",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="default value"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="exclude",
            field=models.BooleanField(
                default=False, verbose_name="exclude from creation"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="foreign_key_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.model",
                verbose_name="foreign key",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="index",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="index",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="is_unique",
            field=models.BooleanField(default=False, verbose_name="unique"),
        ),
        migrations.AlterField(
            model_name="field",
            name="max_digits",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="decimal number length"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="max_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="field length"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="null",
            field=models.BooleanField(
                default=False, verbose_name="allow empty values in database"
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="show_in_detail",
            field=models.BooleanField(default=True, verbose_name="show in detail page"),
        ),
        migrations.AlterField(
            model_name="field",
            name="show_in_list",
            field=models.BooleanField(default=True, verbose_name="show in list page"),
        ),
        migrations.AlterField(
            model_name="field",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="field",
            name="use_index",
            field=models.BooleanField(default=False, verbose_name="create index"),
        ),
        migrations.AlterField(
            model_name="field",
            name="validation_pattern",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="validation pattern"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="model",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="exclude",
            field=models.BooleanField(
                default=False, verbose_name="exclude from creation"
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="index",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="index",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="is_main_entity",
            field=models.BooleanField(default=False, verbose_name="main entry"),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="programminglanguage",
            name="name",
            field=models.CharField(
                max_length=60,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="programming language",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_name",
            field=models.CharField(
                default="admin",
                max_length=60,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="admin user name",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="admin password",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="demo_user_name",
            field=models.CharField(
                blank=True,
                default="demo",
                max_length=60,
                null=True,
                validators=[project.models.NullOrMinLengthValidator(4)],
                verbose_name="demo user name",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="demo_user_password",
            field=models.CharField(
                blank=True,
                help_text="Set no password to disable creation of a demo user!",
                max_length=100,
                null=True,
                validators=[project.models.NullOrMinLengthValidator(6)],
                verbose_name="demo user password",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="domain_name",
            field=models.CharField(
                max_length=100,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="domain",
            ),
        ),
        migrations.AlterField(
            model_name="transformationfile",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "odf", "xls", "xlsx"]
                    )
                ],
                verbose_name="file",
            ),
        ),
    ]
