# Generated by Django 4.1.5 on 2023-01-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0040_alter_codetemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codetemplate",
            name="programming_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programming_languages",
                to="project.programminglanguage",
                verbose_name="programming language",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="project.model",
                verbose_name="table",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="transformation_column",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.transformationcolumn",
                verbose_name="transformation column",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="transformation_headline",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model",
                to="project.transformationheadline",
                verbose_name="headline",
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="project.transformationmapping",
                verbose_name="transformation mapping",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="project.project",
                verbose_name="project settings",
            ),
        ),
        migrations.AlterField(
            model_name="transformationcolumn",
            name="transformation_headline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="project.transformationheadline",
                verbose_name="headline",
            ),
        ),
        migrations.AlterField(
            model_name="transformationfile",
            name="transformation_mapping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="project.transformationmapping",
                verbose_name="transformation mapping",
            ),
        ),
        migrations.AlterField(
            model_name="transformationheadline",
            name="transformation_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="headlines",
                to="project.transformationsheet",
                verbose_name="sheet",
            ),
        ),
        migrations.AlterField(
            model_name="transformationmapping",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="project.project",
                verbose_name="project",
            ),
        ),
        migrations.AlterField(
            model_name="transformationsheet",
            name="transformation_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheets",
                to="project.transformationfile",
                verbose_name="file",
            ),
        ),
    ]
