# Generated by Django 4.1.5 on 2023-01-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0041_alter_codetemplate_programming_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codetemplate",
            options={
                "verbose_name": "Code Template",
                "verbose_name_plural": "Code Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="programminglanguage",
            options={
                "verbose_name": "Programming Language",
                "verbose_name_plural": "Programming Languages",
            },
        ),
    ]
