# Generated by Django 4.1.5 on 2023-01-09 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0042_alter_codetemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codetemplate",
            name="programming_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programming_languages",
                to="project.programminglanguage",
                verbose_name="Programming Language",
            ),
        ),
        migrations.CreateModel(
            name="CodeTemplateParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(4)],
                        verbose_name="name",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="value"
                    ),
                ),
                (
                    "code_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="project.codetemplate",
                        verbose_name="Code Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Template Parameter",
                "verbose_name_plural": "Code Template Parameters",
            },
        ),
    ]
