# Generated by Django 4.1.5 on 2023-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0043_alter_codetemplate_programming_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="docker_root",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="docker root"
            ),
        ),
    ]
