# Generated by Django 4.1.5 on 2023-01-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0044_projectsettings_docker_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="code_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projectsettings",
                to="project.codetemplate",
                verbose_name="Code Template",
            ),
        ),
    ]
