# Generated by Django 4.1.5 on 2023-01-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0045_projectsettings_code_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="codetemplate",
            name="model_exporter",
            field=models.IntegerField(
                choices=[(1, "Java JPA Entities"), (2, "Python Django Models")],
                default=1,
                verbose_name="model exporter type",
            ),
            preserve_default=False,
        ),
    ]
