# Generated by Django 4.1.5 on 2023-01-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0046_codetemplate_model_exporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="datatype",
            field=models.IntegerField(
                choices=[
                    (None, "(Unknown)"),
                    (0, "None"),
                    (1, "BigIntegerField"),
                    (2, "BinaryField"),
                    (3, "BooleanField"),
                    (4, "CharField"),
                    (5, "CommaSeparatedIntegerField"),
                    (6, "DateField"),
                    (7, "DateTimeField"),
                    (8, "DecimalField"),
                    (9, "DurationField"),
                    (10, "EmailField"),
                    (11, "Field"),
                    (12, "FilePathField"),
                    (13, "FloatField"),
                    (14, "GenericIPAddressField"),
                    (15, "IPAddressField"),
                    (16, "IntegerField"),
                    (17, "NullBooleanField"),
                    (18, "PositiveBigIntegerField"),
                    (19, "PositiveIntegerField"),
                    (20, "PositiveSmallIntegerField"),
                    (21, "SlugField"),
                    (22, "SmallAutoField"),
                    (23, "SmallIntegerField"),
                    (24, "TextField"),
                    (25, "TimeField"),
                    (26, "URLField"),
                    (27, "UUIDField"),
                    (28, "AutoField"),
                    (29, "BigAutoField"),
                    (30, "FileField"),
                    (31, "JSONField"),
                ],
                default=4,
                verbose_name="data type",
            ),
        ),
    ]
