# Generated by Django 4.1.5 on 2023-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0047_alter_field_datatype"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationsheet",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
