# Generated by Django 4.1.5 on 2023-01-21 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0050_transformationcolumn_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsettings",
            name="admin_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="admin user email"
            ),
        ),
        migrations.AlterField(
            model_name="projectsettings",
            name="admin_password",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="admin user password",
            ),
        ),
    ]
