# Generated by Django 4.1.5 on 2023-01-22 14:52

import django.core.validators
from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0051_projectsettings_admin_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationmapping",
            name="deployed_archive",
            field=models.FileField(
                blank=True,
                max_length=200,
                null=True,
                upload_to=project.models.deployed_archive_user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip"]
                    )
                ],
                verbose_name="deployed archive",
            ),
        ),
        migrations.AlterField(
            model_name="transformationfile",
            name="file",
            field=models.FileField(
                max_length=200,
                upload_to=project.models.transformation_files_user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv", "odf", "xls", "xlsx"]
                    )
                ],
                verbose_name="file",
            ),
        ),
    ]
